CREATE TABLE IF NOT EXISTS owners(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	phone_number VARCHAR(15) NOT NULL,
	address VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS animal_types(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	animal_type VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS cages(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	animal_type_id INT NOT NULL REFERENCES animal_types(id)
	ON DELETE CASCADE 
	ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS animals(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(30) NOT NULL,
	birthdate DATE NOT NULL,
	owner_id INT REFERENCES owners(id)
	ON DELETE CASCADE 
	ON UPDATE CASCADE,
	animal_type_id INT NOT NULL REFERENCES animal_types(id)
	ON DELETE CASCADE 
	ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS volunteers_departments(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	department_name VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS volunteers(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	phone_number VARCHAR(15) NOT NULL,
	address VARCHAR(50),
	animal_id INT REFERENCES animals(id)
	ON DELETE CASCADE 
	ON UPDATE CASCADE,
	department_id INT NOT NULL REFERENCES volunteers_departments(id)
	ON DELETE CASCADE 
	ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS animals_cages(
	cage_id INT NOT NULL REFERENCES cages(id)
	ON DELETE CASCADE 
	ON UPDATE CASCADE,
	animal_id INT NOT NULL REFERENCES animals(id)
	ON DELETE CASCADE 
	ON UPDATE CASCADE
);